### PR TITLE
refactor datastore package naming and consistency

### PR DESCRIPTION
**Pull request by danchen**
- move classes into datastore packages
- make package name consistent (using datastores)

### CODE REVIEW

**Comment by shadanan** [comment]
:+1:

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by wcekan** [comment]
@danchen Are you sure we needed to rename packages again?  
We now have an inconsistency with the module names: see [repo](https://search.maven.org/#search%7Cga%7C1%7Celide)

**Comment by danchen** [comment]
I didn't change the module name, so it's all the same artifacts. For the module name the singular form that it is already is the best.

**Pull request merged**
