### PR TITLE
Adds Spring Boot 3 Native Image support

### LINKED ISSUE #2934: Spring Boot 3 Native Image support
Would be good if Elide can incorporate support to be compiled as a native image in Spring Boot 3

I noticed the following issues when trying to build a native image

* `ElideConfigProperties` is missing `NestedConfigurationProperty` annotations. Previously it just affected some non essential meta data but during AOT processing this means the reflection meta data configuration is not generated for the nested configuration classes which then silently fail to bind the config properties.
* The `FileLoader` needs changes as Graal will use resources with the `resource` protocol.
* The cache used by the `DefaultClassScanner` needs to be modified to be statically initialized and configured to be loaded at build time `--initialize-at-build-time` along with ClassGraph itself
* A `org.graalvm.nativeimage.hosted.Feature` can be created to register the reflection metadata of classes scanned by ClassGraph
* `@RefreshScope` has issues as a native image so there needs to be a way to make it optional. See https://docs.spring.io/spring-cloud-config/docs/current/reference/html/#_aot_and_native_image_support_2.
* The libraries can incorporate `native-image.properties` to register the approprate metadata of Elide and some of its dependencies

### PR DESCRIPTION
**Pull request by justin-tay**
Resolves #2934 

## Description
- Adds missing `NestedConfigurationProperty` annotation to ElideConfigProperties. Previously it just affected some non essential meta data but during AOT processing this means the reflection meta data configuration is not generated for the nested configuration classes which then silently fail to bind the config properties.
- Modified `FileLoader` for Graal as it use resources with the resource protocol.
- Created a statically initialized cache for `DefaultClassScanner`  and configured to be loaded at build time `--initialize-at-build-time` along with ClassGraph itself
- Created a `org.graalvm.nativeimage.hosted.Feature` to register the reflection metadata of classes scanned by ClassGraph
- Modified `AutoConfiguration` to make `@RefreshScope` optional as there are issues as a native image. See https://docs.spring.io/spring-cloud-config/docs/current/reference/html/#_aot_and_native_image_support_2.
- Added `native-image.properties` to register the appropriate metadata of Elide and some of its dependencies

## Motivation and Context
- Need to get it to compile and run as a native Spring Boot image

## How Has This Been Tested?
- Tested manually by running with the Spring Boot sample

## License
I confirm that this contribution is made under an Apache 2.0 license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Review by aklish — APPROVED** [review]

**Comment by aklish** [comment]
There are some build failures (although this built locally on my mac just fine).  Also, the spring boot example has some errors as well when using GraphQL and running as native.   

```
Caused by: java.lang.IllegalArgumentException: Unable to find class for log/message impl: org.apache.activemq.artemis.core.client.ActiveMQClientMessageBundle_impl
        at org.apache.activemq.artemis.logs.BundleFactory.newBundle(BundleFactory.java:38)
        at org.apache.activemq.artemis.logs.BundleFactory.newBundle(BundleFactory.java:28)
        at org.apache.activemq.artemis.core.client.ActiveMQClientMessageBundle.<clinit>(ActiveMQClientMessageBundle.java:47)
        ... 37 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.apache.activemq.artemis.core.client.ActiveMQClientMessageBundle_impl
```

I will run some additional tests.

**Comment by justin-tay** [comment]
I had updated embedded redis because of this issue https://github.com/codemonstur/embedded-redis/issues/6.

I didn't add the native metadata for artemis into elide itself because I wasn't sure where it was supposed to go so I put it into the example instead https://github.com/justin-tay/elide-spring-boot-example/commit/68e9362332df25582ea2a9fb6ce858b0ed383a2c.

Also the 2.27 version of artemis used jboss-logging which has some issues with native. They switched away from this in 2.28 so that was what I targeted in terms of the native metadata.

**Comment by aklish** [comment]
> I had updated embedded redis because of this issue [codemonstur/embedded-redis#6](https://github.com/codemonstur/embedded-redis/issues/6).
> 
> I didn't add the native metadata for artemis into elide itself because I wasn't sure where it was supposed to go so I put it into the example instead [justin-tay/elide-spring-boot-example@68e9362](https://github.com/justin-tay/elide-spring-boot-example/commit/68e9362332df25582ea2a9fb6ce858b0ed383a2c).
> 
> Also the 2.27 version of artemis used jboss-logging which has some issues with native. They switched away from this in 2.28 so that was what I targeted in terms of the native metadata.

I'm going to merge this, but I was unable to get GraphQL working with the elide-spring-boot example (your branch) for the artemis exception listed earlier.  

Would you be able to also PR the elide-spring-boot-example changes too?  Thanks!

**Review by aklish — APPROVED** [review]

**Comment by justin-tay** [comment]
Sorry I think I missed out some required ActiveMQ and Netty metadata previously for the elide-spring-boot-example changes. The current pull request for elide-spring-boot-example should work.

I also missed out `com.yahoo.elide.graphql.ExecutionResultSerializer` that should be in the `reflect-config.json` in `elide-graphql`.

**Comment by aklish** [comment]
For com.yahoo.elide.graphql.ExecutionResultSerializer, do we just need declaredConstructors or Methods as well?

**Comment by justin-tay** [comment]
Only the declared constructors should be required. I noticed I think I missed out a few serializers and deserializers.

```json
  {
    "name": "com.yahoo.elide.graphql.ExecutionResultDeserializer",
    "allDeclaredConstructors": true
  },
  {
    "name": "com.yahoo.elide.graphql.ExecutionResultSerializer",
    "allDeclaredConstructors": true
  },
  {
    "name": "com.yahoo.elide.graphql.GraphQLErrorDeserializer",
    "allDeclaredConstructors": true
  },
  {
    "name": "com.yahoo.elide.graphql.GraphQLErrorSerializer",
    "allDeclaredConstructors": true
  }
```

**Pull request merged**
