### PR TITLE
Add string to date support

### PR DESCRIPTION
**Pull request by willmsn98**

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by DeathByTape** [comment]
My only question is does this now require a formatted string? Can we accept either long or formatted string?

**Comment by willmsn98** [comment]
I was thinking that users could annotate their bean with either long or java.util.Date.  Date would require a formatted string, but they could also use long if they don't want to use a string.

**Comment by DeathByTape** [comment]
I think that's fair. If we find there are a lot of people who want longs to just work out of the box in the future, we can always add additional support.

👍

**Pull request merged**
