### PR TITLE
Fix date coercion for non-long numeric types

### PR DESCRIPTION
**Pull request by Koka**
Fixes bug #328 by the simpliest available way

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by clayreimann** [comment]
LGTM. Just one question, are we concerned that this also affects floating point numbers?

**Comment by Koka** [comment]
I think case when someone requests to convert floating point number to date is pretty exotic.

**Comment by DeathByTape** [comment]
@clayreimann I agree with @Koka. Maybe that's a bridge we should cross when (if) we get to it

👍

**Comment by xiaoyao1991** [comment]
👍  Thanks @Koka. I'm still having trouble with the last comment I have on #308, which is causing https://github.com/yahoo/elide/pull/320 to not pass. Any idea on that or is it just me

**Comment by Koka** [comment]
@xiaoyao1991 I've looked at latest travis log for your integration test #320  and I can see that there is no exceptions related to date parsing itself, but some logical errors in other tests:

```
  FilterIT.testPublishDateGreaterThanFilterSubRecord:1248 expected [true] but found [false]
  PaginateIT.testPageAndSortOnSubRecords:502 expected [1464638927412] but found [1464638927000]
```

Both failures look like someone is truncating milliseconds on Date fields somewhere.

**Pull request merged**
