### PR TITLE
Add support for usertypes

### PR DESCRIPTION
**Pull request by jkusa**
- Add support for usertypes

### CODE REVIEW

**Comment by danchen** [comment]
You'll want to add your groovy test to: https://github.com/yahoo/elide/blob/master/elide-integration-tests/testngIT.xml

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by danchen** [comment]
Try running against hibernate 5 with: mvn -P hibernate5 clean verify

**Comment by jkusa** [comment]
@danchen Done!

**Comment by danchen** [comment]
:+1:

**Pull request merged**
