### PR TITLE
Don't leak data from relationships

### PR DESCRIPTION
**Pull request by duseja2**

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by DeathByTape** [comment]
Mostly looks good. 2 things that remain:

  1. Need to check the result of `UpdatePermission` when there is no change to a relationship and return that result code (currently it is always `201` which leaves this vulnerable to a brute-force leak).
  1. Please add a unit or integration test for this! :)

**Comment by clayreimann** [comment]
👍  after @DeathByTape's comments are addressed

**Comment by DeathByTape** [comment]
👍

**Pull request merged**
