### PR TITLE
Added quotes to clarify field names in errors.

### PR DESCRIPTION
**Pull request by DeathByTape**

### CODE REVIEW

**Comment by newfront** [comment]
Great Addition. Happy to have these relationships more visible. :shipit:

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by wcekan** [comment]
:+1: :shipit:

**Pull request merged**
