### PR TITLE
Fix building of criteria checks to occur through PermissionExecutor.

### PR DESCRIPTION
**Pull request by DeathByTape**

### CODE REVIEW

**Comment by wcekan** [comment]
Looks fine here for a minimal change to implement a `BypassPermissionExecutor`.
However, would we want more flexibility to customize ParseTree building?

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by wcekan** [comment]
:+1:

**Comment by wcekan** [comment]
:+1: Thank you.  That looks better.

**Pull request merged**
